behaviors:
  ParkingCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048 #
      buffer_size: 4096 #2048
      learning_rate: 0.001 #before it was 0.003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8 #3
      learning_rate_schedule: linear
    network_settings:
      normalize: true #before it was false
      hidden_units: 256 #512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 256 #256
        learning_rate: 0.001 #before it was 0.0003
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 512
    summary_freq: 30000